name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ['1.19', '1.18']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test
          go run math.go
          